version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=diego
      - POSTGRES_USER=diego
      - POSTGRES_DB=diego
      - TZ=America/Bogota  # Agregar la zona horaria

  redis-master:
    container_name: redis-master
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redispassword
      - TZ=America/Bogota  # Agregar la zona horaria
    ports:
      - "6379:6379"

  redis-slave:
    container_name: slave-redis
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_PASSWORD=redispassword
      - TZ=America/Bogota  # Agregar la zona horaria
    ports:
      - "7000:6379"
    depends_on:
      - redis-master

  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    container_name: sentinel-1
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - TZ=America/Bogota  # Agregar la zona horaria
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26379:26379"

  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    container_name: sentinel-2
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - TZ=America/Bogota 
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26380:26379"

  redis-sentinel-3:
    image: 'bitnami/redis-sentinel:latest'
    container_name: sentinel-3
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - TZ=America/Bogota  
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26381:26379"

  springboot-app:
    image: springboot-app
    build: .
    environment:
      - URL_FLY=jdbc:postgresql://postgres:5432/diego
      - URL_R=r2dbc:postgresql://postgres:5432/diego
      - REDIS=redis
      - TZ=America/Bogota  
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis-master
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3

volumes:
  redis-data:
    driver: local
