version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=diego
      - POSTGRES_USER=diego
      - POSTGRES_DB=diego

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
