spring:
  flyway:
    url: ${URL_FLY}
    user: diego
    password: diego
    baseline-on-migrate: true
  application:
    name: diego
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - redis-sentinel-1:26379
          - redis-sentinel-2:26380
          - redis-sentinel-3:26381
      password: redispassword
  r2dbc:
    password: diego
    url: ${URL_R}
    username: diego
logging:
  level:
    org:
      flywaydb: trace
      springframework:
        data:
          redis:
            cache: trace
            nodeValue: trace
        cache:
          nodeValue: trace
          interceptor: trace
